version: '3'

networks:
  hohoho:

services:
  books-api:
    build:
      context: .
      args:
        - VER=1.0
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - hohoho


  postgres:
    image: postgres:latest
    restart: on-failure
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_DB: db_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aebnm
    ports:
      - "8001:5432"
    networks:
      - hohoho

